import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google';
import {Providers} from "@/components/Providers";
import React from "react";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import ThemeRegistry from "@/app/ThemeRegistry";

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
    <html lang="en">
      <body
          className={poppins.className}
      >
      <ThemeRegistry>{children}</ThemeRegistry>
      <ToastContainer/>
      </body>
    </html>
    </Providers>
  );
}
